# Generated by Django 3.1.7 on 2021-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('low', 'low'), ('middle', 'middle'), ('high', 'high')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
