# Generated by Django 3.1.7 on 2021-03-27 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('myapp', '0003_questionnaires_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('time_to_die', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            bases=('authtoken.token',),
        ),
    ]
